# Please follow the order and template below to tag items
#   tags for paper type:
#     - book
#     - preprint
#     - journal
#     - conference
#   tags for research themes:
#     - casual interactions
#     - brain dynamics
#     - neuro disorders
#     - image reconstruction
#   tags for other properties (limited to 2):
#     - open science
#     - other (e.g., recognition)

#Seeburger-PNAS-2026
- id: doi:10.31234/osf.io/qzv47_v1
  type: journal
  authors: 
  - Dolly Tan Seeburger
  - Jason Tsukahara
  - Nan Xu
  - Vishwadeep Ahluwalia
  - Shella Keilholz
  - Randall W Engle
  tags:
    - preprint
    - brain dynamics

#Xu-SoftwareX-2025
- id: doi:10.1016/j.softx.2025.102067
  type: journal
  buttons:
    - type: source
      text: code
      link: https://github.com/imnanxu/QPPLab
  tags:
    - journal
    - brain dynamics
    
#Anumba-IN-2024
- id: doi:10.1162/imag_a_00314
  type: journal
  tags:
    - journal
    - brain dynamics
    - cross-species
    - neuro disorders

#Meyer-Baese-FT-2024
- id: doi:10.3389/fnsys.2024.1425491
  type: journal
  tags:
    - journal
    - brain dynamics
    - cross-species

#Seeburger-CABN-2024
#Time-varying functional connectivity predicts fluctuations in sustained attention in a serial tapping task.
- id: doi:10.3758/s13415-024-01156-1
  type: journal
  tags:
    - journal
    - brain dynamics

#Anumba-MRM-2023
- id: doi:10.1002/mrm.29824
  type: journal
  tags:
    - journal
    - brain dynamics
    - cross-species

#Xu-Aperture-2023
- id: doi:10.52294/001c.85075
  type: journal
  description: "> **Featured at the Aperture Symposium of the OHBM 2024 Annual Meeting!**"
  buttons:
    - type: youtube
      text: "tutorial"
      link: https://www.youtube.com/playlist?list=PLzl6lxEF9yCb3i0Coc5noXWzINKqWXTOd
    - type: source
      text: code
      link: https://github.com/GT-EmoryMINDlab/rodent-whole-brain-preprocessing-recipe 
  tags:
    - journal
    - preprocessing
    - open science
    - recognition

#Xu-ImagNeuro-2023
- id: doi:10.1162/imag_a_00002
  type: journal
  description: "Employed the statistical inferences techniques to study the interplay between infraslow dynamic processes and visual perceptions. Discovered that these intrinsic dynamic processes are notably resilient in humans, as contrast with anesthetized rodents (Belloy et al., 2021). Yet, their stability can still be affected in diverse ways: they can swamp an overlapping BOLD response evoked by the flickering checkerboard, but their phase-locked waveform can still be modulated by different sequences of stimuli that affects the reaction time and sustained attention."
  image: papers/images/xu-in-2023.png
  buttons:
    - type: source
      text: preprocessing code
      link: https://github.com/imnanxu/PartialHumanBrain_preprocessing
    - type: source
      text: analysis code
      link: https://github.com/imnanxu/QPPLab
  tags:
    - journal
    - brain dynamics
    - open science

#Anumba-ad-2022-missed Nan's name
- id: doi:10.1002/alz.061608
  authors: 
  - Nmachi Anumba
  - Michael Kelberman
  - Corrie Smith
  - Wen Ju Pan
  - Perrin G Clavijo
  - Nan Xu
  - Alexia Marriott
  - Ellen Kim
  - David Weinshenker
  - Shella Keilholz
  tags:
  - conference
  - neuro disorders

#Xu-FT-2022-rev
- id: doi:10.3389/fnins.2022.816331
  type: journal
  # image: https://www.frontiersin.org/files/Articles/816331/fnins-16-816331-HTML/image_m/fnins-16-816331-g003.jpg
  tags:
  - journal
  - brain dynamics
  - cross-species

#Xu-NI-2021
- id: doi:10.1016/j.neuroimage.2020.117628
  type: journal
  description: 
  image: papers/images/xu-ni-2021-brain.jpg
  buttons:
  - type: source
    text: code
    link: https://www.mathworks.com/matlabcentral/fileexchange/62781-pcorrelation
  tags:
  - journal
  - causal interactions
  - discovery

#Xu-SISC-2021
- id: doi:10.1137/20M1318183
  type: journal
  image: papers/images/xu-sisc-2021.png
  buttons:
    - type: source
      text: code
      link: https://github.com/imnanxu/PolyhedralBasisFunction/releases/tag/sisc2021
    - type: source
      text: numerical solutions
      link: https://github.com/imnanxu/PolyhedralBasisFunction/releases/tag/sisc2021
  tags:
  - journal
  - scientific computing
  - image reconstruction
  - theory

#keilholz-ft-2020
- id: doi:10.3389/fnins.2020.550923
  type: journal
  tags:
  - journal
  - brain dynamics

#Xu-LabAn-2019
- id: doi:10.1038/s41684-019-0326-6
  type: journal
  link: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8102135/
  authors: 
    - Nan Xu+
    - Dhaval S Patel+ 
    - Hang Lu  
  description: +equal contributions
  tags:
    - journal
    - deep phenotyping
    - big data
  buttons:
    - type: journal
      text: manuscript
      link: https://arxiv.org/pdf/1904.01096
 # image: papers/images/xu-labanimal-2019.png

#Xu-TIP-2019
- id: doi:10.1109/tip.2019.2915631
  image: papers/images/xu-TIP-2019.png
  type: journal
  description: Using cryo-EM, we transform highly noisy and randomly-oriented projection images of 103─106 virus particles into a 3D model of the virus. Unlike traditional methods that assume strict geometric symmetry, we adopted a more realistic approach, allowing individual particles to be asymmetric while maintaining symmetry in the overall mean and covariance. This novel method eliminates long-standing distortions along the symmetry axes. 
  tags:
  - journal
  - image reconstruction
  buttons:
    - type: journal
      text: manuscript
      link: https://arxiv.org/pdf/1701.01206


# Xu-FT-2017
- id: doi:10.3389/fnins.2017.00271
  type: journal
  description: "We developed p-corr, an innovative algorithm enhancing traditional correlation analysis with a causal dynamic model. P-corr identifies information flow in functional connectivity, maintains sensitivity in detecting modular architecture, and scales to handle hundreds of ROIs for comprehensive whole-brain connectivity assessments."
  image: papers/images/xu-ft-2017-pcorr.png
  buttons:
  - type: source
    text: code
    link: https://www.mathworks.com/matlabcentral/fileexchange/62781-pcorrelation
  tags:
  - journal
  - causal interactions
  - modeling


#Xu-JSB-2016
- id: doi:10.1016/j.jsb.2017.12.013
  # image: papers/images/xu-jsb-2016.png
  type: journal
  description: "We developed a cyro-EM image reconstruction algortihm for virus particles, allowing for asymmetry and eliminating distortions along symmetry axes (Xu & Doerschuk, 2019). In collaboration with virologists from the Scripps Institute, we uncovered allosteric effects along the symmetry axes of the bacteriophage HK97."
  tags:
  - journal
  - image reconstruction

#doeschuk-opinion-2016
- id: doi:10.1016/j.coviro.2016.02.011
#  type: journal
# image: papers/images/doerschuk-opinion-virology-2016.png
  tags:
  - journal
  - image reconstruction

#xu-embc-2016
- id: doi:10.1109/embc.2016.7591598
  type: conference
  publisher: IEEE Engineering In Medicine And Biology Society Annual International Conference
  description: "> **EMBS Student Paper Competition Finalist - Top 0.4% conference proceedings!**"
  link: https://ieeexplore.ieee.org/document/7591598
  buttons:
    - type: paper
      text: proceedings
      link: "/papers/manuscripts/xu-embc-2016.pdf"
  tags:
  - conference
  - image reconstruction
  - recognition

#xu-spie-2015
- id: doi:10.1117/12.2193791
  type: conference
  description: "> **Top 10% Paper Recognition; Top 34 papers demonstrated in the Show & Tell session!**"
  buttons:
    - type: paper
      text: proceedings
      link: "/papers/manuscripts/xu-spie-2015.pdf"
  tags:
  - conference
  - image reconstruction
  - recognition

#xu-icip-2015
- id: doi:10.1109/ICIP.2015.7351039
  type: conference
  buttons:
    - type: paper
      text: proceedings
      link: "/papers/manuscripts/xu-icip-2015.pdf"
  tags:
  - conference
  - image reconstruction

#xu-icip-2014
- id: doi:10.1109/ICIP.2014.7025712
  type: conference
  buttons:
    - type: paper
      text: proceedings
      link: "/papers/manuscripts/xu-icip-2014.pdf"
  tags:
  - conference
  - causal interactions
  - modeling

#xu-imagoptics-2014
- id: doi:10.1364/srs.2014.stu3f.4
  type: conference
  buttons:
    - type: paper
      text: proceedings
      link: "/papers/manuscripts/xu-srs-2014.pdf"
  tags:
  - conference
  - image reconstruction


###################################################################
###################################################################
##################### Abstracts w/o official ids ################
###################################################################
###################################################################
- #id: ohbm2026
  title: "Validation of channel capacity as an effective connectivity measure in fMRI"
  authors:
    - Jianan Jian
    - Benjamin Li
    - Nurahmed Multezem
    - Francesca Mandino
    - Evelyn Lake
    - Nan Xu
  publisher: Organization for Human Brain Mapping 2026 Annual Meeting
  date: '2026-06-14
  type: conference
  tags:
    - conference
    - causal interactions
    - brain dynamics

- #id: ohbm2025
  title: "Sliding-window prediction correlation (SWpC): a sensitive approach for detecting task-specific directed functional connectivity dynamics"
  authors:
    - Nan Xu
    - Vince D. Calhoun
    - Shella D. Keilholz
  publisher: Organization for Human Brain Mapping 2025 Annual Meeting
  date: '2025-06-24'
  type: conference
  tags:
    - conference
    - causal interactions
    - brain dynamics
    - modeling
    
- #id: ohbm2024i
  title: "The effects of locus coeruleus stimulation on quasi-periodic patterns in rats"
  authors:
    - Nmachi Anumba
    - Michael A. Keilberman
    - Wenju Pan
    - Alexia Marriott
    - Nan Xu
    - David Weinshenker
    - Shella Keilholz
  publisher: Organization for Human Brain Mapping 2024 Annual Meeting
  date: '2024-06-23'
  type: conference
  tags: 
    - conference
    - brain dynamics
    - cross-species

- #id: ohbm2024ii
  title: "Time-varying causal interactions in the functional brain networks: modeling and validation"
  authors:
    - Nan Xu
    - Xiaodi Zhang
    - Wenju Pan
    - Jeremy L. Smith
    - Jason W. Allen
    - Vince D. Calhoun
    - Shella D. Keilholz
  publisher: Organization for Human Brain Mapping 2024 Annual Meeting
  date: '2024-06-23'
  type: conference
  tags:
    - conference
    - causal interactions
    - brain dynamics
    - modeling
    - neuro disorders

- #id: bic2024i
  title: "Modeling and validation of dynamic causal interactions in functional brain network"
  authors:
    - Nan Xu
    - Xiaodi Zhang
    - Wenju Pan
    - Jeremy L. Smith
    - Jason W. Allen
    - Vince D. Calhoun
    - Shella D. Keilholz
  publisher: 10th Annual BRAIN Initiative Conference
  date: '2024-06-18'
  type: conference
  tags:
    - conference
    - causal interactions
    - brain dynamics
    - modeling
    - neuro disorders

- #id: asfnr2023i
  title: "``Hyperconnected'' vestibular state in subacute and chronic post-concussive vestibular dysfunction using dynamic whole brain functional connectivity analysis"
  description: "> **Oral Presentation.**"
  authors:
    - Anna Trofimova
    - Jeremy Smith
    - Nan Xu
    - Shella Keilholz
    - Russell Gore
    - Jason W. Allen
  publisher: The 16th Annual Meeting of the American Society of Functional Neuroradiology
  date: '2023-10-07'
  type: conference
  tags:
    - conference
    - brain dynamics
    - neuro disorders
    - recognition

- #id: ohbm2023i
  title: "Distribution of large-scale spatiotemporal patterns within and across individuals"
  authors:
    - Taylor Bolt
    - Nan Xu
    - Laren Daley
    - T.J. LaGrow
    - W-J Pan
    - Eric Schumacher
    - Shella Keilholz
  publisher: Organization for Human Brain Mapping 2023 Annual Meeting
  date: '2023-07-22'
  type: conference
  tags:
    - conference
    - brain dynamics

- #id: ohbm2023ii
  title: "The interaction between visual stimulation and intrinsic infraslow whole brain activity in humans"
  authors:
    - Nan Xu
    - Derek Smith
    - George Geno
    - Dolly T. Seeburger
    - Eric H. Schumacher
    - Shella D. Keilholz
  publisher: Organization for Human Brain Mapping 2023 Annual Meeting
  date: '2023-07-22'
  type: conference
  tags:
    - conference
    - brain dynamics

- #id: ohbm2022i
  title: "Dynamic spatiotemporal interactions in vestibular networks affected by concussive syndromes"
  authors:
    - Nan Xu
    - Jeremy Smith
    - Jason Allen
    - Shella Keilholz
  publisher: Organization for Human Brain Mapping 2022 Annual Meeting
  date: '2022-06-19'
  type: conference
  tags:
    - conference   
    - causal interactions
    - neuro disorders

- #id: cns2022i
  title: "Investigating the relationship between sustained attention and quasi-periodic brain activity patterns with the psychomotor vigilance task."
  authors:
    - Yunji Lee
    - Dolly T. Seeburger
    - Sakshi Dhawan
    - Tiffany Nguyen
    - Nan Xu
    - Marcus Ma
    - Anzar Abbas
    - Waqas Majeed
    - Garth Thompson
    - Shella D. Keilholz
    - Eric H. Schumacher
  publisher: Cognitive Neuroscience Society 2022 Annual Meeting
  date: '2022-04-23'
  type: conference
  tags:
    - conference
    - brain dynamics
    - cognitive functions

- #id: cns2022ii
  title: "Identifying the neural mechanisms of zone state performance using time-varying functional connectivity methods."
  description: "> **Oral Presentation.**"
  authors:
    - Dolly T. Seeburger
    - Nan Xu
    - C Godwin
    - Marcus Ma
    - Shella D. Keilholz
    - Eric H. Schumacher
  publisher: Cognitive Neuroscience Society 2022 Annual Meeting
  date: '2022-04-23'
  type: conference
  tags:
    - conference
    - brain dynamics
    - cognitive functions
    - recognition

- #id: ohbm2021i
  title: "Quasiperiodic patterns and BOLD response entrained by visual stimulation in the human brain."
  authors:
    - Nan Xu
    - Derek M. Smith
    - George Jeno
    - Dolly T. Seeburger
    - Eric H. Schumacher
    - Shella D. Keilholz
  publisher: Organization for Human Brain Mapping 2021 Annual Meeting
  date: '2021-05-30'
  type: conference
  tags:
    - conference
    - brain dynamics
    - cognitive functions

- #id: ohbm2020i
  title: "Investigation of spatiotemporal functional interactivity among large-scale brain networks"
  description: "> **Oral Presentation; Selected 4% of Accepted Abstract Papers.**"
  authors:
    - Nan Xu
    - R Nathan Spreng
    - Shella D. Keilholz
  publisher: Organization for Human Brain Mapping 2020 Annual Meeting
  date: '2020-06-23'
  type: conference
  tags:
    - conference
    - causal interactions
    - cognitive functions
    - recognition

- #id: embs2016i
  title: "What are the most talkative brain regions?"
  publisher: IEEE Engineering In Medicine And Biology Society Annual International Conference
  description: "> **Late-breaking Research Paper!**"
  authors:
    - Nan Xu
    - Peter C. Doerschuk
    - R Nathan Spreng
  date: '2016-08-01'
  type: conference
  tags:
    - conference
    - causal interactions
    - recognition

- #id: cns2014i
  title: "Directed interactivity of large-scale brain networks: Introducing a new method for estimating brain connectivity MRI"
  authors:
    - Nan Xu
    - R Nathan Spreng
    - Peter C. Doerschuk
  publisher: Cognitive Neuroscience Society 2014 Annual Meeting
  date: '2014-04-07'
  type: conference
  tags:
    - conference
    - causal interactions
